// Scaffolds for new OGF projects. Each creates a minimal but runnable
// skeleton that follows the conventions doc. Codex's first turn fills
// in the gameplay; OGF's editor stays useful from minute one.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { EngineKind } from '@ogf/contracts';
import { godotConventions, webConventions } from './conventions.js';

interface ScaffoldFile {
  rel: string;
  body: string;
}

interface BootstrapResult {
  files: string[];
}

function writeIfMissing(rootAbs: string, files: ScaffoldFile[]): string[] {
  const written: string[] = [];
  for (const f of files) {
    const abs = path.join(rootAbs, f.rel);
    if (existsSync(abs)) continue;
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, f.body, 'utf8');
    written.push(f.rel);
  }
  return written;
}

// ---------- Godot ----------

const GODOT_PROJECT = (name: string) => `; Auto-generated by Open Game Forge.
; Edit through the Project Settings dialog or here directly.

config_version=5

[application]

config/name="${name}"
run/main_scene="res://scenes/Main.tscn"
config/features=PackedStringArray("4.5")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"

[rendering]

renderer/rendering_method="gl_compatibility"
`;

const GODOT_MAIN_TSCN = `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/Main.gd" id="1"]

[node name="Main" type="Node2D"]
script = ExtResource("1")
`;

const GODOT_MAIN_GD = `extends Node2D

# Auto-generated entry point. Replace with your game's logic.
# Convention: load gameplay data from data/*.json (see .ogf/conventions.md).

func _ready() -> void:
\tprint("OGF project — Main.tscn loaded")

func _load_json(path: String) -> Variant:
\tvar text := FileAccess.get_file_as_string(path)
\treturn JSON.parse_string(text)
`;

const GODOT_GITIGNORE = `# Godot
.godot/
*.tmp
*.import.bak

# OGF
.ogf/
`;

function godotFiles(name: string, conventions: string): ScaffoldFile[] {
  return [
    { rel: 'project.godot', body: GODOT_PROJECT(name) },
    { rel: 'scenes/Main.tscn', body: GODOT_MAIN_TSCN },
    { rel: 'scripts/Main.gd', body: GODOT_MAIN_GD },
    { rel: '.gitignore', body: GODOT_GITIGNORE },
    { rel: '.ogf/conventions.md', body: conventions },
    { rel: 'data/.gitkeep', body: '' },
    { rel: 'assets/.gitkeep', body: '' },
  ];
}

// ---------- Web ----------

const WEB_INDEX = (name: string) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${name}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <main>
      <canvas id="game" width="1280" height="720"></canvas>
    </main>
    <script type="module" src="src/game.js"></script>
  </body>
</html>
`;

const WEB_STYLES = `* { box-sizing: border-box; }
body {
  margin: 0;
  background: #111;
  color: #ddd;
  font-family: system-ui, sans-serif;
  display: grid;
  place-items: center;
  min-height: 100vh;
}
canvas {
  display: block;
  background: #000;
  image-rendering: pixelated;
  max-width: 100%;
  height: auto;
}
`;

const WEB_GAME_JS = `// Auto-generated entry point. The pipeline below is what makes the
// OGF Scenes tab "live" — it reads the level JSON every load, so anything
// you drag in OGF (or that Codex writes into data/*.json) shows up here
// without touching this file.
//
// Replace the loop body with your gameplay; keep the data-loading pattern.
// See .ogf/conventions.md for the full level schema.

const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');

async function loadJSON(rel) {
  const r = await fetch(rel);
  if (!r.ok) throw new Error(\`fetch \${rel}: \${r.status}\`);
  return await r.json();
}

function loadImage(rel) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(\`could not load \${rel}\`));
    img.src = rel;
  });
}

/** Resize canvas to match the level's map size (so OGF coords === pixel coords). */
function fitCanvas(level) {
  const m = level.mapSize ?? { width: 1280, height: 720 };
  if (canvas.width !== m.width) canvas.width = m.width;
  if (canvas.height !== m.height) canvas.height = m.height;
}

/** Pre-load every \`props[*].image\` path into a { path → HTMLImageElement } map. */
async function loadPropImages(level) {
  const images = {};
  const srcs = new Set();
  for (const p of level.props ?? []) if (p.image) srcs.add(p.image);
  await Promise.all(
    [...srcs].map(async (src) => {
      try { images[src] = await loadImage(src); } catch (e) { console.warn(e); }
    }),
  );
  return images;
}

async function start() {
  // The list of levels is in data/levels.json — start with the first one.
  // (When you add more levels, write a router / level-switcher here.)
  const levels = await loadJSON('data/levels.json');
  const first = levels.levels?.[0];
  const level = await loadJSON(first?.file ?? 'data/level1.json');

  fitCanvas(level);

  let bg = null;
  if (level.background) {
    try { bg = await loadImage(level.background); } catch (e) { console.warn(e); }
  }
  const propImages = await loadPropImages(level);

  function drawProp(p) {
    // Convention: (p.x, p.y) is the BOTTOM-CENTER anchor — x is the center,
    // y is the feet / ground line. Same convention OGF uses when dragging.
    const img = propImages[p.image];
    if (!img) return;
    ctx.drawImage(img, p.x - p.w / 2, p.y - p.h, p.w, p.h);
  }

  function frame() {
    if (bg) {
      ctx.drawImage(bg, 0, 0, canvas.width, canvas.height);
    } else {
      ctx.fillStyle = '#1a1a1a';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
    }

    // Painter's algorithm: z-sort by sortY (fall back to y).
    const props = (level.props ?? [])
      .slice()
      .sort((a, b) => (a.sortY ?? a.y) - (b.sortY ?? b.y));
    for (const p of props) drawProp(p);

    if ((level.props ?? []).length === 0 && !bg) {
      ctx.fillStyle = '#888';
      ctx.font = '20px system-ui';
      ctx.fillText('Empty level. Add props in OGF\\'s Scenes tab,', 40, 60);
      ctx.fillText('or ask Codex to generate a background + props.', 40, 90);
    }

    requestAnimationFrame(frame);
  }
  frame();
}

start().catch((err) => {
  console.error(err);
  ctx.fillStyle = '#400';
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = '#fcc';
  ctx.font = '16px system-ui';
  ctx.fillText('start() failed: ' + err.message, 20, 30);
});
`;

const WEB_LEVELS_JSON = `{
  "levels": [
    { "id": "level1", "file": "data/level1.json" }
  ]
}
`;

const WEB_LEVEL1_JSON = `{
  "id": "level1",
  "background": "assets/maps/level1.png",
  "mapSize": { "width": 1280, "height": 720 },
  "spawn": { "x": 640, "y": 600 },
  "exits": {},
  "zones": {},
  "walkBounds": [],
  "blockers": [],
  "spawn_points": [],
  "props": []
}
`;

const WEB_GITIGNORE = `# OGF
.ogf/

# Editor / OS
.DS_Store
node_modules/
`;

function webFiles(name: string, conventions: string): ScaffoldFile[] {
  return [
    { rel: 'index.html', body: WEB_INDEX(name) },
    { rel: 'styles.css', body: WEB_STYLES },
    { rel: 'src/game.js', body: WEB_GAME_JS },
    { rel: 'data/levels.json', body: WEB_LEVELS_JSON },
    { rel: 'data/level1.json', body: WEB_LEVEL1_JSON },
    { rel: '.gitignore', body: WEB_GITIGNORE },
    { rel: '.ogf/conventions.md', body: conventions },
    { rel: 'assets/maps/.gitkeep', body: '' },
    { rel: 'assets/sprites/.gitkeep', body: '' },
  ];
}

// ---------- Entry ----------

export function bootstrapProject(opts: {
  rootAbs: string;
  engine: EngineKind;
  name: string;
}): BootstrapResult {
  mkdirSync(opts.rootAbs, { recursive: true });
  let files: ScaffoldFile[];
  if (opts.engine === 'godot') {
    files = godotFiles(opts.name, godotConventions());
  } else if (opts.engine === 'web') {
    files = webFiles(opts.name, webConventions());
  } else {
    throw new Error(`Bootstrap not yet supported for engine: ${opts.engine}`);
  }
  const written = writeIfMissing(opts.rootAbs, files);
  return { files: written };
}
