// Scaffolds for new OGF projects. Each creates a minimal but runnable
// skeleton that follows the conventions doc. Codex's first turn fills
// in the gameplay; OGF's editor stays useful from minute one.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { EngineKind } from '@ogf/contracts';
import { godotConventions, webConventions } from './conventions.js';

interface ScaffoldFile {
  rel: string;
  body: string;
}

interface BootstrapResult {
  files: string[];
}

function writeIfMissing(rootAbs: string, files: ScaffoldFile[]): string[] {
  const written: string[] = [];
  for (const f of files) {
    const abs = path.join(rootAbs, f.rel);
    if (existsSync(abs)) continue;
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, f.body, 'utf8');
    written.push(f.rel);
  }
  return written;
}

// ---------- Godot ----------

const GODOT_PROJECT = (name: string) => `; Auto-generated by Open Game Forge.
; Edit through the Project Settings dialog or here directly.

config_version=5

[application]

config/name="${name}"
run/main_scene="res://scenes/Main.tscn"
config/features=PackedStringArray("4.5")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"

[rendering]

renderer/rendering_method="gl_compatibility"
`;

const GODOT_MAIN_TSCN = `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/Main.gd" id="1"]

[node name="Main" type="Node2D"]
script = ExtResource("1")
`;

const GODOT_MAIN_GD = `extends Node2D

# Auto-generated entry point. Replace with your game's logic.
# Convention: load gameplay data from data/*.json (see .ogf/conventions.md).

func _ready() -> void:
\tprint("OGF project — Main.tscn loaded")

func _load_json(path: String) -> Variant:
\tvar text := FileAccess.get_file_as_string(path)
\treturn JSON.parse_string(text)
`;

const GODOT_GITIGNORE = `# Godot
.godot/
*.tmp
*.import.bak

# OGF
.ogf/
`;

function godotFiles(name: string, conventions: string): ScaffoldFile[] {
  return [
    { rel: 'project.godot', body: GODOT_PROJECT(name) },
    { rel: 'scenes/Main.tscn', body: GODOT_MAIN_TSCN },
    { rel: 'scripts/Main.gd', body: GODOT_MAIN_GD },
    { rel: '.gitignore', body: GODOT_GITIGNORE },
    { rel: '.ogf/conventions.md', body: conventions },
    { rel: 'data/.gitkeep', body: '' },
    { rel: 'assets/.gitkeep', body: '' },
  ];
}

// ---------- Web ----------

const WEB_INDEX = (name: string) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${name}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <main>
      <canvas id="game" width="1280" height="720"></canvas>
    </main>
    <script type="module" src="src/game.js"></script>
  </body>
</html>
`;

const WEB_STYLES = `* { box-sizing: border-box; }
body {
  margin: 0;
  background: #111;
  color: #ddd;
  font-family: system-ui, sans-serif;
  display: grid;
  place-items: center;
  min-height: 100vh;
}
canvas {
  display: block;
  background: #000;
  image-rendering: pixelated;
  max-width: 100%;
  height: auto;
}
`;

const WEB_GAME_JS = `// Auto-generated entry point. Replace with your game's logic.
// Convention: keep gameplay data in data/*.json (see .ogf/conventions.md).

const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');

async function loadJSON(rel) {
  const r = await fetch(rel);
  return await r.json();
}

async function loadImage(rel) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = rel;
  });
}

async function start() {
  // const level = await loadJSON('data/level1.json');
  // const bg = await loadImage(level.background);
  // ctx.drawImage(bg, 0, 0, level.mapSize.width, level.mapSize.height);
  ctx.fillStyle = '#1a1a1a';
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = '#888';
  ctx.font = '24px system-ui';
  ctx.fillText('OGF web project — load a level from data/*.json', 40, 80);
}

start();
`;

const WEB_LEVELS_JSON = `{
  "levels": [
    { "id": "level1", "file": "data/level1.json" }
  ]
}
`;

const WEB_LEVEL1_JSON = `{
  "id": "level1",
  "background": "assets/maps/level1.png",
  "mapSize": { "width": 1280, "height": 720 },
  "spawn": { "x": 640, "y": 600 },
  "exits": {},
  "zones": {},
  "walkBounds": [],
  "blockers": [],
  "spawn_points": [],
  "props": []
}
`;

const WEB_GITIGNORE = `# OGF
.ogf/

# Editor / OS
.DS_Store
node_modules/
`;

function webFiles(name: string, conventions: string): ScaffoldFile[] {
  return [
    { rel: 'index.html', body: WEB_INDEX(name) },
    { rel: 'styles.css', body: WEB_STYLES },
    { rel: 'src/game.js', body: WEB_GAME_JS },
    { rel: 'data/levels.json', body: WEB_LEVELS_JSON },
    { rel: 'data/level1.json', body: WEB_LEVEL1_JSON },
    { rel: '.gitignore', body: WEB_GITIGNORE },
    { rel: '.ogf/conventions.md', body: conventions },
    { rel: 'assets/maps/.gitkeep', body: '' },
    { rel: 'assets/sprites/.gitkeep', body: '' },
  ];
}

// ---------- Entry ----------

export function bootstrapProject(opts: {
  rootAbs: string;
  engine: EngineKind;
  name: string;
}): BootstrapResult {
  mkdirSync(opts.rootAbs, { recursive: true });
  let files: ScaffoldFile[];
  if (opts.engine === 'godot') {
    files = godotFiles(opts.name, godotConventions());
  } else if (opts.engine === 'web') {
    files = webFiles(opts.name, webConventions());
  } else {
    throw new Error(`Bootstrap not yet supported for engine: ${opts.engine}`);
  }
  const written = writeIfMissing(opts.rootAbs, files);
  return { files: written };
}
