const state = {
  mode: "choose",
  scene: "outdoor",
  partnerId: null,
  // Boss / quest flags keyed by id (e.g. "gate", "boss", "templeApprentice",
  // "templeMaster", "marshBoss", "mistScout", "mistGuard", "mistMaster").
  // Add a new boss = add a new key here, no other state.js touch needed.
  flags: {},
  choiceIndex: 0,
  battleActionIndex: 0,
  battleSwitchIndex: 0,
  menuIndex: 0,
  menuSubIndex: 0,
  menuDetail: null,
  partnerProgress: {},
  partnerHp: {},
  ownedMitama: [],
  inventory: {},
  seenDex: {},
  player: {
    x: 0,
    y: 0,
    dir: "up",
    moving: false,
  },
  keys: new Set(),
  dialogueQueue: [],
  pendingBattle: null,
  pendingSceneChange: null,
  sceneExitCooldown: 0,
  battle: null,
  encounterCharge: 0,
  lastSavedAt: 0,
  menuMessage: "",
  debugCollision: false,
  transition: null,
};
